'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class DeckOfCards
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Game.DeckOfCards", GetType(DeckOfCards).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _10_of_Clubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_10_of_Clubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _10_of_Diamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_10_of_Diamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _10_of_Hearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_10_of_Hearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _10_of_Spades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_10_of_Spades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _2_of_Clubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2_of_Clubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _2_of_Diamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2_of_Diamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _2_of_Hearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2_of_Hearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _2_of_Spades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2_of_Spades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _3_of_Clubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_3_of_Clubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _3_of_Diamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_3_of_Diamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _3_of_Hearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_3_of_Hearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _3_of_Spades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_3_of_Spades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _4_of_Clubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_4_of_Clubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _4_of_Diamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_4_of_Diamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _4_of_Hearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_4_of_Hearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _4_of_Spades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_4_of_Spades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _5_of_Clubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_5_of_Clubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _5_of_Diamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_5_of_Diamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _5_of_Hearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_5_of_Hearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _5_of_Spades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_5_of_Spades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _6_of_Clubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_6_of_Clubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _6_of_Diamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_6_of_Diamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _6_of_Hearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_6_of_Hearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _6_of_Spades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_6_of_Spades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _7_of_Clubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_7_of_Clubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _7_of_Diamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_7_of_Diamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _7_of_Hearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_7_of_Hearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _7_of_Spades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_7_of_Spades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _8_of_Clubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_8_of_Clubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _8_of_Diamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_8_of_Diamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _8_of_Hearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_8_of_Hearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _8_of_Spades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_8_of_Spades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _9_of_Clubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_9_of_Clubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _9_of_Diamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_9_of_Diamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _9_of_Hearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_9_of_Hearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _9_of_Spades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_9_of_Spades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Ace_of_Clubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ace_of_Clubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Ace_of_Diamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ace_of_Diamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Ace_of_Hearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ace_of_Hearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Ace_of_Spades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ace_of_Spades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Jack_of_Clubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jack_of_Clubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Jack_of_Diamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jack_of_Diamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Jack_of_Hearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jack_of_Hearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Jack_of_Spades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jack_of_Spades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property King_of_Clubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("King_of_Clubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property King_of_Diamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("King_of_Diamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property King_of_Hearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("King_of_Hearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property King_of_Spades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("King_of_Spades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Queen_of_Clubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Queen_of_Clubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Queen_of_Diamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Queen_of_Diamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Queen_of_Hearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Queen_of_Hearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Queen_of_Spades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Queen_of_Spades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
